// CopyNinja All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace PlayerGameplayTags
{
	/* Input Tags */
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipSword);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipSword);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword);

	/* Player Tags */
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);

	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword);

	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword);
	HACKNSLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword);

}